// Laravel/Laravel 12/app7/resources/js/pages/Users/Show.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'User Details',
        href: 'users',
    },
];

defineProps({
    user: Object,
    userRole: Array
});
</script>

<template>
    <Head title="User Details" />
    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link :href="`/users`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Back to Users
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                    <div className="flex items-center space-x-5">
                        <div className="flex-1 mx-3 my-2">
                            <h2 className="text-xl font-bold text-gray-900 mb-1">{{user.name}}</h2>
                            <p className="text-xs text-gray-500 mb-2">Joined: <span className="font-medium">{{user.created_at}}</span></p>
                            <hr className="my-2" />
                            <div className="text-sm text-gray-700">
                                <span className="font-semibold">Email:</span> {{user.email}}
                            </div>
                            
                            <div className="text-sm text-gray-700">
                                <span className="font-semibold">Role:
                                    <samp v-for="role in userRole" key="1"
                                        class="m-1 bg-gray-100 text-gray-800 text-sm font-medium rounded-md px-0.5 py-0.5">
                                        {{ role }}
                                    </samp>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

// Back-End/Laravel_12_ReactJS_VueJS/app3/resources/js/pages/Users/Show.tsx
import { PlaceholderPattern } from '@/components/ui/placeholder-pattern';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'User Details',
        href: '/users',
    },
];

export default function UserDetails({ user, userRoles }) {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="User Details" />
            <div className='container mx-auto p-4'>
                <div className='flex justify-between items-center mb-4'>
                    <h1 className='text-2xl font-bold mb-4'>Edit User</h1>
                    <Link href='/users' className='mt-8 block rounded-md bg-gray-900 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-gray-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10'>Back to Users</Link>
                </div>

                <div className="max-w-lg mx-auto bg-white rounded-xl shadow-md overflow-hidden p-6">
                    <div className="flex items-center space-x-5">
                        <div className="flex-1">
                            <h2 className="text-xl font-bold text-gray-900 mb-1">{user.name}</h2>
                            <p className="text-xs text-gray-500 mb-2">Joined: <span className="font-medium">{user.created_at}</span></p>
                            <hr className="my-2" />
                            <div className="text-sm text-gray-700">
                                <span className="font-semibold">Email:</span> {user.email}
                            </div>
                            <div className="text-sm text-gray-700 mt-1">
                                <span className="font-semibold">Roles:</span>
                                {userRoles.map((role) => (
                                    <span key={role} className="inline-block px-2 mx-0.5 py-1 my-0.5 mx-0.5 text-xs font-medium text-white bg-amber-600 rounded-full">
                                        {role}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </AppLayout>
    );
}
