// Laravel/Laravel 12/app5/resources/js/pages/Roles/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { index } from '@/routes/users';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Role Create',
        href: 'roles',
    },
];

defineProps({
    permissions: Array
})

const form = useForm({
    name: '',
    permissions: [],
});
</script>

<template>

    <Head title="Role Create" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link :href="`/roles`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Back to Roles
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 bg-white border-b border-gray-200">
                        <form @submit.prevent="form.post('/roles')"
                            class="max-w-lg mx-auto space-y-6 bg-white p-6 rounded-lg shadow">
                            <div>
                                <label htmlFor="name" class="block text-sm font-medium text-gray-700">
                                    Role Name
                                </label>
                                <input type="text" id="name" name="name"
                                    class="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    v-model="form.name" />
                                <p v-if="form.errors.name" class="mt-2 text-sm text-red-600">{{ form.errors.name }}
                                </p>
                            </div>

                            <div class="flex flex-col">
                                <label class='font-bold my-1'>Permissions:</label>

                                <div v-for="permission in permissions" class="flex items-center mb-2">
                                    <input type="checkbox" name="permissions" v-model="form.permissions" :value="permission"
                                        :id="`permission-${permission}`"
                                        class="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500" />
                                    <label :for="`permission-${permission}`"
                                        class="ml-2 block text-sm text-gray-700 capitalize">
                                        {{ permission }}
                                    </label>
                                </div>
                                <p v-if="form.errors.permissions" class="mt-2 text-sm text-red-600">{{
                                    form.errors.permissions }}
                                </p>
                            </div>
                            <hr />
                            <button type="submit" :disabled="form.processing"
                                class="cursor-pointer w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold shadow hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ form.processing ? 'Loading...' : 'Submit' }}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

// Back-End/Laravel_12_ReactJS_VueJS/app3/resources/js/pages/Roles/Create.tsx
import { PlaceholderPattern } from '@/components/ui/placeholder-pattern';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Role Create',
        href: '/roles',
    },
];

export default function RolesCreate({ permissions }) {
    const { data, setData, post, reset, processing, errors } = useForm({
        name: '',
        permissions: [],
    });

    const handleCheckboxChange = (permissionName, checked) => {
        if (checked) {
            setData('permissions', [...data.permissions, permissionName]);
        } else {
            setData('permissions', data.permissions.filter((id) => id !== permissionName));
        }
    };

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        post(route('roles.store'), {
            onSuccess: () => {
                reset();
            },
        });
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Create Role" />
            <div className='container mx-auto p-4'>
                <div className='flex justify-between items-center mb-4'>
                    <h1 className='text-2xl font-bold mb-4'>Create Role</h1>
                    <Link href='/roles' className='mt-8 block rounded-md bg-gray-900 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-gray-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10'>Back to Roles</Link>
                </div>

                <form onSubmit={submit} className="max-w-lg mx-auto space-y-6 bg-white p-6 rounded-lg shadow">
                    <div>
                        <label htmlFor="name" className="block text-sm font-medium text-gray-700">
                            Role Name
                        </label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            className="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            value={data.name}
                            onChange={(e) => setData('name', e.target.value)}
                        />
                        {errors.name && <div className="text-red-500 text-sm">{errors.name}</div>}
                    </div>

                    <label htmlFor="" className='font-bold my-1'>Permissions</label>
                    {Object.keys(permissions).length === 0 ? (
                        <div className="text-gray-500">No permissions available</div>
                    ) : (
                        <div className="flex flex-col">
                            {permissions.map((permission) => (
                                <div key={permission} className="flex items-center mb-2">
                                    <input
                                        type="checkbox"
                                        value={permission}
                                        onChange={(e) => handleCheckboxChange(permission, e.target.checked)}
                                        id={permission}
                                        className="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                                    />
                                    <label htmlFor={permission} className="ml-2 block text-sm text-gray-700">
                                        {permission}
                                    </label>
                                </div>
                            ))}
                        </div>
                    )}
                    {errors.permissions && <div className="text-red-500 text-sm">{errors.permissions}</div>}
                    <hr />
                    <button
                        type="submit"
                        className="cursor-pointer w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold shadow hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        {processing ? 'Loading...' : 'Submit'}
                    </button>
                </form>
            </div>

        </AppLayout>
    );
}
