// Laravel/Laravel 12/app1/resources/js/pages/Posts/Create.tsx
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Posts',
        href: '/posts',
    },
];

export default function CreatePost() {

        const { data, setData, post, reset, processing, errors } = useForm({
            title: '',
            contect: '',
            image: null,
        });

        const submit = (e: React.FormEvent) => {
            e.preventDefault();
            post('/posts', {
                onSuccess: () => {
                    reset();
                },
            });
        };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Create Post" />
            <div className='container mx-auto p-4'>
                <div className='flex justify-between items-center mb-4'>
                    <h1 className='text-2xl font-bold mb-4'>Create Post</h1>
                    <Link href='/posts' className='mt-8 block rounded-md bg-gray-900 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-gray-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10'>Back to Posts</Link>
                </div>

                <form onSubmit={submit} method="post" encType='multipart/form-data'>
                    <div className='mb-4'>
                        <label htmlFor="title" className='block text-sm font-medium mb-2'>Title</label>
                        <input type="text" id="title" name="title" className='mt-1 block w-full border px-3 py-2 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500' value={data.title} onChange={e => setData('title', e.currentTarget.value)} />

                        {errors.title && <p className='mt-2 text-sm text-red-600'>{errors.title}</p>}
                    </div>
                    <div className='mb-4'>
                        <label htmlFor="contect" className='block text-sm font-medium mb-2'>Contect</label>
                        <textarea id="contect" name="contect" className='mt-1 block w-full border px-3 py-2 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500' rows={3} value={data.contect} onChange={e => setData('contect', e.currentTarget.value)}></textarea>
                        {errors.contect && <p className='mt-2 text-sm text-red-600'>{errors.contect}</p>}
                    </div>
                    <div className='mb-4'>
                        <label htmlFor="image" className='block text-sm font-medium mb-2'>Image</label>
                        <input type="file" id="image" name="image" className='mt-1 block w-full border px-3 py-2 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500' onChange={e => setData('image', e.currentTarget.files[0])} />
                        {errors.image && <p className='mt-2 text-sm text-red-600'>{errors.image}</p>}
                    </div>
                    <button type="submit" className='mt-8 block rounded-md bg-indigo-500 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10 cursor-pointer'>
                        {processing ? 'Creating...' : 'Create Post'}
                    </button>
                </form>
            </div>
        </AppLayout>
    );
}

// Laravel/Laravel 12/app5/resources/js/pages/Roles/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { index } from '@/routes/users';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Role Create',
        href: 'roles',
    },
];

defineProps({
    permissions: Array
})

const form = useForm({
    name: '',
    permissions: [],
});
</script>

<template>

    <Head title="Role Create" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link :href="`/roles`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Back to Roles
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 bg-white border-b border-gray-200">
                        <form @submit.prevent="form.post('/roles')"
                            class="max-w-lg mx-auto space-y-6 bg-white p-6 rounded-lg shadow">
                            <div>
                                <label htmlFor="name" class="block text-sm font-medium text-gray-700">
                                    Role Name
                                </label>
                                <input type="text" id="name" name="name"
                                    class="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    v-model="form.name" />
                                <p v-if="form.errors.name" class="mt-2 text-sm text-red-600">{{ form.errors.name }}
                                </p>
                            </div>

                            <div class="flex flex-col">
                                <label class='font-bold my-1'>Permissions:</label>

                                <div v-for="permission in permissions" class="flex items-center mb-2">
                                    <input type="checkbox" name="permissions" v-model="form.permissions" :value="permission"
                                        :id="`permission-${permission}`"
                                        class="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500" />
                                    <label :for="`permission-${permission}`"
                                        class="ml-2 block text-sm text-gray-700 capitalize">
                                        {{ permission }}
                                    </label>
                                </div>
                                <p v-if="form.errors.permissions" class="mt-2 text-sm text-red-600">{{
                                    form.errors.permissions }}
                                </p>
                            </div>
                            <hr />
                            <button type="submit" :disabled="form.processing"
                                class="cursor-pointer w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold shadow hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ form.processing ? 'Loading...' : 'Submit' }}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
