// Laravel/Laravel 12/app4.1-3.1/resources/js/pages/Roles/Index.tsx
import { PlaceholderPattern } from '@/components/ui/placeholder-pattern';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, router } from '@inertiajs/react';
import { can } from '@/lib/can';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Roles',
        href: '/roles',
    },
];

export default function Roles({ roles }) {
    const handleDelete = (id) => {
        if (confirm('Are you sure you want to delete this role?')) {
            router.delete(route('roles.destroy', id));
        }
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Roles" />

            <div className='container mx-auto p-4'>
                <div className="flex justify-between items-center mb-6">
                    <h1 className="text-2xl font-bold">All Roles</h1>
                    { can('roles.create') && (
                    <Link
                        href="/roles/create"
                        className="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white shadow hover:bg-gray-950 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Create Role
                    </Link>
                    )}
                </div>

                <div className='overflow-x-auto'>
                    <table className='w-full table-auto shadow-lg bg-white dark:bg-neutral-800 rounded-lg'>
                        <thead>
                            <tr className='bg-neutral-50 dark:bg-neutral-700'>
                                <th className='px-4 py-2'>#</th>
                                <th className='px-4 py-2'>Roles</th>
                                <th className='px-4 py-2'>Permissions</th>
                                <th className='px-4 py-2'>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {roles.map((role, index) => (
                                <tr key={role.id} className={index % 2 === 0 ? 'bg-white dark:bg-neutral-800' : 'bg-neutral-50 dark:bg-neutral-700'}>
                                    <td className='border px-4 py-2'>{index + 1}</td>
                                    <td className='border px-4 py-2'>{role.name}</td>
                                    <td className='border px-4 py-2'>
                                        {role.permissions.map((permission) =>
                                            <span key={permission.id} className="inline-block bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full mr-1">
                                                {permission.name}
                                            </span>
                                        )}
                                    </td>
                                    <td className='border px-4 py-2 text-center'>
                                        {can('roles.view') && (
                                            <Link href={route('roles.show', role.id)} className='cursor-pointer px-3 py-1 mx-1 text-sm font-xs font-medium rounded-md text-white bg-green-600'>
                                                View
                                            </Link>
                                        )}
                                        {can('roles.edit') && (
                                            <Link href={route('roles.edit', role.id)} className='cursor-pointer px-3 py-1 mx-1 text-sm font-xs font-medium rounded-md text-white bg-blue-600'>
                                                Edit
                                            </Link>
                                        )}
                                        {can('roles.delete') && (
                                            <Link onClick={() => handleDelete(role.id)} className='cursor-pointer px-3 py-1 mx-1 text-sm font-xs font-medium rounded-md text-white bg-red-600'>
                                                Delete
                                            </Link>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </AppLayout>
    );
}

// Back-End/Laravel_12_ReactJS_VueJS/app7/resources/js/pages/Roles/Index.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { can } from '@/lib/can';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, router } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Roles & Permissions',
        href: 'roles',
    },
];
defineProps({
    roles: Array
})

function deleteRole(id) {
    if (confirm("Are you sure you want to delete this role?")) {
        router.delete(`/roles/${id}`);
    }
}

</script>

<template>

    <Head title="Roles & Permissions" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link v-if="can('roles.create')" :href="`/roles/create`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Create Role
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 bg-white border-b border-gray-200">
                        <div className='overflow-x-auto'>
                            <table class="w-full table-auto rounded-lg">
                                <thead>
                                    <tr>
                                        <th class="border px-4 py-2">ID</th>
                                        <th class="border px-4 py-2">Role</th>
                                        <th class="border px-4 py-2">Permissions</th>
                                        <th class="border px-4 py-2">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="(role, index) in roles" :key="role.id">
                                        <td class="border px-4 py-2">{{ index + 1 }}</td>
                                        <td class="border px-4 py-2">{{ role.name }}</td>
                                        <td class="border px-4 py-2">
                                            <samp v-for="permission in role.permissions" key="1"
                                                class="m-1 bg-green-100 text-green-800 text-sm font-medium rounded-md px-0.5 py-0.5">
                                                {{ permission.name }}
                                            </samp>
                                        </td>
                                        <td class="border px-4 py-2">
                                            <Link v-if="can('roles.edit')" :href="`/roles/${role.id}/edit`"
                                                class="cursor-pointer text-white bg-blue-500 rounded-md px-3 py-1 m-0.5">
                                            Edit
                                            </Link>

                                            <Link v-if="can('roles.delete')" @click="deleteRole(role.id)"
                                                class="cursor-pointer text-white bg-red-500 rounded-md px-3 py-1 m-0.5">
                                            Delete
                                            </Link>

                                            <Link v-if="can('roles.view')" :href="`/roles/${role.id}`"
                                                class="cursor-pointer text-white bg-green-500 rounded-md px-3 py-1 m-0.5">
                                            View
                                            </Link>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
