// Laravel/Laravel 12/app4.1-3.1/resources/js/pages/Roles/Show.tsx
import { PlaceholderPattern } from '@/components/ui/placeholder-pattern';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Role Details',
        href: '/roles',
    },
];

export default function RoleDetails({ role, permissions }) {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Role Details" />
            <div className='container mx-auto p-4'>
                <div className='flex justify-between items-center mb-4'>
                    <h1 className='text-2xl font-bold mb-4'>Edit Role</h1>
                    <Link href='/roles' className='mt-8 block rounded-md bg-gray-900 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-gray-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10'>Back to Roles</Link>
                </div>

                <div className="max-w-lg mx-auto bg-white rounded-xl shadow-md overflow-hidden p-6">
                    <div className="flex items-center space-x-5">
                        <div className="flex-1">
                            <h2 className="text-xl font-bold text-gray-900 mb-1">{role.name}</h2>
                            <p className="text-xs text-gray-500 mb-2">Created At: <span className="font-medium">{role.created_at}</span></p>
                            <hr className="my-2" />
                            <div className="text-sm text-gray-700">
                                <span className="font-semibold">Permissions:</span>
                                {/* {permissions.join(', ')} */}
                                {permissions.map((permission) =>
                                    <span key={permission} className="inline-block bg-blue-100 text-blue-800 text-xs px-2 py-1 my-0.5 mx-0.5 rounded-full">
                                        {permission}
                                    </span>
                                )}
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </AppLayout>
    );
}

// Back-End/Laravel_12_ReactJS_VueJS/app7/resources/js/pages/Roles/Show.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import roles from '@/routes/roles';
import { type BreadcrumbItem } from '@/types';
import { Head, Link } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Role Details',
        href: 'roles',
    },
];

defineProps({
    role: Object,
    rolePermission: Array,
});
</script>

<template>

    <Head title="Role Details" />
    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link :href="`/roles`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Back to Roles
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                    <div className="flex items-center space-x-5">
                        <div className="flex-1 mx-3 my-2">
                            <h2 className="text-xl font-bold text-gray-900 mb-1">{{ role.name }}</h2>
                            <p className="text-xs text-gray-500 mb-2">Joined: <span className="font-medium">{{
                                role.created_at }}</span></p>
                            <hr className="my-2" />
                            <div className="text-sm text-gray-700">
                                <span className="font-semibold">Permission:
                                    <samp v-for="permission in rolePermission" key="1"
                                        class="m-1 bg-gray-100 text-gray-800 text-sm font-medium rounded-md px-0.5 py-0.5">
                                        {{ permission }}
                                    </samp>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
