// Laravel/Laravel 12/app6/resources/js/components/Pagination.vue
<script setup>
import { Link } from '@inertiajs/vue3';

defineProps({
    links: {
        type: Array,
        required: true
    }
})
</script>

<template>
    <div class="flex flex-wrap item-center space-x-1 mt-4">
        <Link v-for="(link, index) in links" :key="index" :href="link.url || '#'" v-html="link.label"
            class="px-3 py-1 text-sm rounded border" :class="[
                link.active ? 'bg-blue-600 text-white' : 'bg-white text-gray-700',
                !link.url ? 'opacity-50 pointer-events-none' : 'hover:bg-gray-100'
            ]" />
    </div>
</template>

// Laravel/Laravel 12/app4/resources/js/components/Pagination.tsx
import { Link } from "@inertiajs/react";

export default function Pagination({ links }) {
    return (
        <div className="mt-4 flex justify-center">
            {links.map((link) => (
                <Link
                    key={link.label}
                    href={link.url ?? '#'}
                    dangerouslySetInnerHTML={{ __html: link.label }}
                    className={`px-3 py-1 border border-gray-300 rounded hover:bg-gray-100 
                        ${link.active ? 'bg-gray-300' : 'bg-white'} ${!link.url ? 'pointer-events-none text-gray-400' : 'text-gray-600'}`}
                >
                </Link>
            ))
            }
        </div >
    );
}
