// Laravel/Laravel 12/app4.1-3.1/resources/js/pages/Users/Create.tsx
import { PlaceholderPattern } from '@/components/ui/placeholder-pattern';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'User Create',
        href: '/users',
    },
];

export default function UsersCreate({ roles }) {
    const { data, setData, post, reset, processing, errors } = useForm({
        name: '',
        email: '',
        password: '',
        roles: [],
    });

    const handleCheckboxChange = (roleName, checked) => {
        if (checked) {
            setData('roles', [...data.roles, roleName]);
        } else {
            setData('roles', data.roles.filter((id) => id !== roleName));
        }
    };

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        post(route('users.store'), {
            onSuccess: () => {
                reset();
            },
        });
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Create User" />
            <div className='container mx-auto p-4'>
                <div className='flex justify-between items-center mb-4'>
                    <h1 className='text-2xl font-bold mb-4'>Create User</h1>
                    <Link href='/users' className='mt-8 block rounded-md bg-gray-900 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs hover:bg-gray-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500 sm:mt-10'>Back to Users</Link>
                </div>

                <form onSubmit={submit} className="max-w-lg mx-auto space-y-6 bg-white p-6 rounded-lg shadow">
                    <div>
                        <label htmlFor="name" className="block text-sm font-medium text-gray-700">
                            Name
                        </label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            className="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            value={data.name}
                            onChange={(e) => setData('name', e.target.value)}
                        />
                        {errors.name && <div className="text-red-500 text-sm">{errors.name}</div>}
                    </div>

                    <div>
                        <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                            Email
                        </label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            className="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            value={data.email}
                            onChange={(e) => setData('email', e.target.value)}
                        />
                        {errors.email && <div className="text-red-500 text-sm">{errors.email}</div>}
                    </div>

                    <div>
                        <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                            Password
                        </label>
                        <input
                            type="password"
                            id="password"
                            name="password"
                            className="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            value={data.password}
                            onChange={(e) => setData('password', e.target.value)}
                        />
                        {errors.password && <div className="text-red-500 text-sm">{errors.password}</div>}
                    </div>

                    <label htmlFor="" className='font-bold my-1'>Roles:</label>
                    {Object.keys(roles).length === 0 ? (
                        <div className="text-gray-500">No roles available</div>
                    ) : (
                        <div className="flex flex-col">
                            {roles.map((roles) => (
                                <div key={roles} className="flex items-center mb-2">
                                    <input
                                        type="checkbox"
                                        value={roles}
                                        onChange={(e) => handleCheckboxChange(roles, e.target.checked)}
                                        id={roles}
                                        className="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                                    />
                                    <label htmlFor={roles} className="ml-2 block text-sm text-gray-700">
                                        {roles}
                                    </label>
                                </div>
                            ))}
                        </div>
                    )}
                    {errors.roles && <div className="text-red-500 text-sm">{errors.roles}</div>}

                    <hr />
                    <button
                        type="submit"
                        className="cursor-pointer w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold shadow hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        {processing ? 'Loading...' : 'Submit'}
                    </button>
                </form>
            </div>
        </AppLayout >
    );
}

// Laravel/Laravel 12/app7/resources/js/pages/Users/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import roles from '@/routes/roles';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, useForm } from '@inertiajs/vue3';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'User Create',
        href: 'users',
    },
];

defineProps({
    role: Array
})

const form = useForm({
    name: '',
    email: '',
    password: '',
    roles: [],
});

</script>

<template>

    <Head title="User Create" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <Link :href="`/users`"
                    class="mb-4 inline-block rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-950">
                Back to Users
                </Link>
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 bg-white border-b border-gray-200">
                        <form @submit.prevent="form.post('/users')"
                            class="max-w-lg mx-auto space-y-6 bg-white p-6 rounded-lg shadow">
                            <div>
                                <label htmlFor="name" class="block text-sm font-medium text-gray-700">
                                    Name
                                </label>
                                <input type="text" id="name" name="name"
                                    class="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    v-model="form.name" />
                                <p v-if="form.errors.name" class="mt-2 text-sm text-red-600">{{ form.errors.name }}</p>
                            </div>

                            <div>
                                <label htmlFor="email" class="block text-sm font-medium text-gray-700">
                                    Email
                                </label>
                                <input type="email" id="email" name="email"
                                    class="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    v-model="form.email" />
                                <p v-if="form.errors.email" class="mt-2 text-sm text-red-600">{{ form.errors.email }}
                                </p>
                            </div>

                            <div>
                                <label htmlFor="password" class="block text-sm font-medium text-gray-700">
                                    Password
                                </label>
                                <input type="password" id="password" name="password"
                                    class="mt-1 px-2 py-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    v-model="form.password" />
                                <p v-if="form.errors.password" class="mt-2 text-sm text-red-600">{{ form.errors.password
                                }}</p>
                            </div>

                            <div class="flex flex-col">
                                <label class='font-bold my-1'>Roles:</label>

                                <div v-for="role in role" class="flex items-center mb-2">
                                    <input type="checkbox" name="role" v-model="form.roles" :value="role"
                                        :id="`role-${role}`"
                                        class="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500" />
                                    <label :for="`role-${role}`" class="ml-2 block text-sm text-gray-700 capitalize">
                                        {{ role }}
                                    </label>
                                </div>
                                <p v-if="form.errors.roles" class="mt-2 text-sm text-red-600">{{
                                    form.errors.roles }}
                                </p>
                            </div>

                            <hr />
                            <button type="submit" :disabled="form.processing"
                                class="cursor-pointer w-full rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold shadow hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ form.processing ? 'Loading...' : 'Submit' }}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
